const locators = {
  "Button with Text": `(//button[normalize-space()='+'])[1]`,
  "Button with Text Add New Address": `//button[normalize-space()='Add New Address']`,
  "Button with Text Add to Cart": `//button[normalize-space()='Add to Cart']`,
  "Button with Text ADD TO CART": `//button[normalize-space()='ADD TO CART']`,
  "Button with Text Add to Cart_1": `(//button[normalize-space()='Add to Cart'])[2]`,
  "Button with Text Add to Cart_2": `(//button[normalize-space()='Add to Cart'])[1]`,
  "Button with Text Additional information": `//button[normalize-space()='Additional information']`,
  "Button with Text Back to home": `//button[normalize-space()='Back to home']`,
  "Button with Text Cancel": `(//button[normalize-space()='Cancel'])[2]`,
  "Button with Text Cancel_1": `(//button[normalize-space()='Cancel'])[4]`,
  "Button with Text Cash on Delivery": `//button[normalize-space()='Cash on Delivery']`,
  "Button with Text Change": `(//button[normalize-space()='Change'])[1]`,
  "Button with Text Checkout": `//button[normalize-space()='Checkout']`,
  "Button with Text Checkout_1": `(//button[normalize-space()='Checkout'])[2]`,
  "Button with Text Continue Shopping": `//button[normalize-space()='Continue Shopping']`,
  "Button with Text Create Account": `//button[normalize-space()='Create Account']`,
  "Button with Text Delete": `//button[normalize-space()='Delete']`,
  "Button with Text Filters": `//button[normalize-space()='Filters']`,
  "Button with Text Place Order": `//button[normalize-space()='Place Order']`,
  "Button with Text Reset All Filters": `//button[normalize-space()='Reset All Filters']`,
  "Button with Text Reset Filters": `//button[normalize-space()='Reset Filters']`,
  "Button with Text Reviews": `//button[normalize-space()='Reviews']`,
  "Button with Text Save Address": `//button[normalize-space()='Save Address']`,
  "Button with Text Save Changes": `//button[normalize-space()='Save Changes']`,
  "Button with Text Security": `//button[normalize-space()='Security']`,
  "Button with Text Shop Now": `(//button[normalize-space()='Shop Now'])[1]`,
  "Button with Text Sign in": `//button[normalize-space()='Sign in']`,
  "Button with Text Update Address": `//button[normalize-space()='Update Address']`,
  "Button with Text Update Password": `//button[normalize-space()='Update Password']`,
  "Button with Text View": `(//button[normalize-space()='View'])[1]`,
  "Button with Text View Cart": `//button[normalize-space()='View Cart']`,
  "Button with Text Yes Cancel Order": `//button[normalize-space()='Yes, Cancel Order']`,
  "Button with Text_1": `(//button[normalize-space()='+'])[2]`,
  "Button with title Delete address": `(//button[@title='Delete address'])[2]`,
  "Button with title Delete address_1": `(//button[@title='Delete address'])[1]`,
  "Div": `(//div/div[1])[8]`,
  "Div starting with Text Password": `(//div[starts-with(normalize-space(), 'Password')])[2]`,
  "Div starting with Text Rode NT1-A Condenser Mic": `(//div[starts-with(normalize-space(), 'Rode NT1-A Condenser Mic')])[1]`,
  "Div with role status": `div[role="status"]`,
  "Div with Text Add new address": `//div[normalize-space()='Add new address']`,
  "Div with Text Added to the cart": `(//div[normalize-space()='Added to the cart'])[3]`,
  "Div with Text Address added successfully": `(//div[normalize-space()='Address added successfully'])[3]`,
  "Div with Text Address deleted successfully": `(((//div[normalize-space()='Address deleted successfully'])[3]//div)[1]//div)[2]//div`,
  "Div with Text Filters": `((//div[normalize-space()='Filters']//div)[2]//button)[2]`,
  "Div with Text Logged in successfully": `(//div[normalize-space()='Logged in successfully'])[3]`,
  "Div with Text My Account": `//div[normalize-space()='My Account']`,
  "Div with Text My Wishlist": `//div[normalize-space()='My Wishlist']`,
  "Div with Text Order cancelled successfully": `(//div[normalize-space()='Order cancelled successfully'])[3]`,
  "Div_1": `(((//div[1]/div[2])[7]//div)[11]//div)[4]`,
  "Div_10": `(//div[2]/div)[16]`,
  "Div_11": `(//div[2]/div)[37]`,
  "Div_2": `(//div[3]/div)[8]`,
  "Div_3": `(//div[1]/div[2])[9]`,
  "Div_4": `(//div/div[1])[22]`,
  "Div_5": `(//div[2]/div)[18]`,
  "Div_6": `(//div/div[1])[21]`,
  "Div_7": `(//div/div[2])[17]`,
  "Div_8": `(//div/div[2])[16]`,
  "Div_9": `(((//div[1]/div[2])[7]//div)[12]//div)[10]`,
  "H1 with Text All Products": `//h1[normalize-space()='All Products']`,
  "H1 with Text Checkout": `//h1[normalize-space()='Checkout']`,
  "H1 with Text My Wishlist": `//h1[normalize-space()='My Wishlist']`,
  "H1 with Text Order Details": `//h1[normalize-space()='Order Details']`,
  "H1 with Text Shopping Cart": `//h1[normalize-space()='Shopping Cart']`,
  "H2 with Text My Addresses": `//h2[normalize-space()='My Addresses']`,
  "H2 with Text Sign In": `//h2[normalize-space()='Sign In']`,
  "H2 with Text Thank You": `//h2[normalize-space()='Thank You, !']`,
  "H3 with Text Your order is confirmed": `//h3[normalize-space()='Your order is confirmed']`,
  "Html": `html[lang="en"] > body > div:nth-of-type(1)`,
  "Html inside body": `(((//html[@lang='en']//body//div)[1]//div)[37]//div)[1]`,
  "Html inside body_1": `((((//html[@lang='en']//body//div)[1]//div)[39]//div)[11]//button)[2]`,
  "Html inside body_10": `(((((//html[@lang='en']//body//div)[1]//section//div)[1]//div)[5]//div)[1]//div)[1]//select`,
  "Html inside body_11": `((//html[@lang='en']//body//div)[1]//div)[37]`,
  "Html inside body_12": `((((//html[@lang='en']//body//div)[1]//div)[37]//div)[1]//div)[2]`,
  "Html inside body_13": `((//html[@lang='en']//body//div)[1]//section//div)[1]`,
  "Html inside body_14": `(((((((//html[@lang='en']//body//div)[1]//div)[39]//div)[1]//div)[1]//div)[1]//div)[2]//div)[1]`,
  "Html inside body_15": `((((//html[@lang='en']//body//div)[1]//div)[38]//div)[2]//div)[2]`,
  "Html inside body_16": `((((((//html[@lang='en']//body//div)[1]//section//div)[1]//div)[6]//a)[8]//div)[1]//div)[1]//img`,
  "Html inside body_17": `(((//html[@lang='en']//body//div)[1]//div)[39]//div)[1]`,
  "Html inside body_18": `((((((//html[@lang='en']//body//div)[1]//div)[1]//div)[3]//div)[1]//div)[6]//div)[3]`,
  "Html inside body_19": `((//html[@lang='en']//body//div)[1]//div)[31]`,
  "Html inside body_2": `((//html[@lang='en']//body//div)[1]//div)[39]`,
  "Html inside body_20": `(((((//html[@lang='en']//body//div)[1]//div)[38]//section)[3]//div)[1]//div)[1]`,
  "Html inside body_21": `(((((((//html[@lang='en']//body//div)[1]//div)[1]//div)[3]//div)[1]//div)[6]//div)[3]//div)[1]`,
  "Html inside body_22": `((((((//html[@lang='en']//body//div)[1]//div)[39]//div)[1]//div)[1]//div)[1]//div)[2]`,
  "Html inside body_23": `((//html[@lang='en']//body//div)[1]//div)[26]`,
  "Html inside body_24": `(((((((//html[@lang='en']//body//div)[1]//div)[39]//div)[2]//div)[9]//div)[2]//div)[2]//div)[3]`,
  "Html inside body_25": `((//html[@lang='en']//body//div)[1]//div)[38]`,
  "Html inside body_26": `((((//html[@lang='en']//body//div)[1]//div)[39]//div)[27]//button)[2]`,
  "Html inside body_3": `(((//html[@lang='en']//body//div)[1]//div)[38]//div)[2]`,
  "Html inside body_4": `((//html[@lang='en']//body//div)[1]//div)[1]`,
  "Html inside body_5": `(((((((//html[@lang='en']//body//div)[1]//div)[26]//div)[1]//div)[1]//div)[1]//div)[2]//div)[1]`,
  "Html inside body_6": `(((//html[@lang='en']//body//div)[1]//div)[15]//div)[2]`,
  "Html inside body_7": `((((//html[@lang='en']//body//div)[1]//div)[38]//section)[3]//div)[1]`,
  "Html inside body_8": `((((//html[@lang='en']//body//div)[1]//div)[1]//div)[3]//div)[1]`,
  "Html inside body_9": `((((//html[@lang='en']//body//div)[1]//div)[39]//div)[19]//button)[2]`,
  "Html_1": `html[lang="en"] > body`,
  "Html_2": `html[lang="en"]`,
  "Img with alt dp": `(//img[@alt='dp'])[5]`,
  "Img with alt Go Pro HERO10 Black": `img[alt="GoPro HERO10 Black"]`,
  "Img with alt JBL Charge 4 Bluetooth Speaker": `img[alt="JBL Charge 4 Bluetooth Speaker"]`,
  "Img with alt Rode NT1-A Condenser Mic": `img[alt="Rode NT1-A Condenser Mic"]`,
  "Img with alt Seagate 4TB External Hard Drive": `img[alt="Seagate 4TB External Hard Drive"]`,
  "Input with name city": `input[name="city"]`,
  "Input with name confirm Password": `input[name="confirmPassword"]`,
  "Input with name contact Number": `input[name="contactNumber"]`,
  "Input with name country": `input[name="country"]`,
  "Input with name email": `input[name="email"]`,
  "Input with name first Name": `input[name="firstName"]`,
  "Input with name firstname": `input[name="firstname"]`,
  "Input with name lastname": `input[name="lastname"]`,
  "Input with name password": `input[name="password"]`,
  "Input with name state": `input[name="state"]`,
  "Input with name street": `input[name="street"]`,
  "Input with name zip Code": `input[name="zipCode"]`,
  "Input with placeholder Search products": `input[placeholder="Search products..."]`,
  "Input with value 0": `input[value="0"]`,
  "Input with value 24000": `input[value="24000"]`,
  "Input with value 29000": `input[value="29000"]`,
  "Input with value 35000": `input[value="35000"]`,
  "Input with value 36000": `input[value="36000"]`,
  "Input with value 41000": `input[value="41000"]`,
  "Input with value 62000": `input[value="62000"]`,
  "Input with value 74000": `input[value="74000"]`,
  "Label with Text Country": `//label[normalize-space()='Country']`,
  "Li with Text All Products": `(//li[normalize-space()='All Products'])[1]`,
  "P": `//p[contains(text(), 'silver business point surat gu')]`,
  "P with Text Addresses": `//p[normalize-space()='Addresses']`,
  "P with Text Enter a 10-digit phone number": `//p[normalize-space()='Enter a 10-digit phone number']`,
  "P with Text Log Out": `//p[normalize-space()='Log Out']`,
  "P with Text My Orders": `//p[normalize-space()='My Orders']`,
  "P with Text Sign out of your account": `//p[normalize-space()='Sign out of your account']`,
  "P with Text Track and manage your orders": `//p[normalize-space()='Track and manage your orders']`,
  "Span with Text 1": `//span[normalize-space()='1']`,
  "Span with Text 2": `//span[normalize-space()='2']`,
  "Span with Text Back to home": `//span[normalize-space()='Back to home']`,
  "Span with Text Checkout": `//span[normalize-space()='Checkout']`,
  "Span with Text Filters": `//span[normalize-space()='Filters']`,
  "Span with Text Sign up": `//span[normalize-space()='Sign up']`,
  "SVG": `svg[data-icon="eye"]`,
  "SVG Path inside SVG": `//*[name()='svg'][.//*[name()='path' and contains(@d,'M25.1578 1')]]`,
  "SVG Path inside SVG_1": `//*[name()='svg'][.//*[name()='path' and contains(@d,'M22 19.638')]]`,
  "SVG Path inside SVG_10": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M360 184h-')]])[1]`,
  "SVG Path inside SVG_11": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M923 283.6')]])[8]`,
  "SVG Path inside SVG_2": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M923 283.6')]])[1]`,
  "SVG Path inside SVG_3": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M832 312H6')]])[2]`,
  "SVG Path inside SVG_4": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M923 283.6')]])[2]`,
  "SVG Path inside SVG_5": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M482 152h6')]])[1]`,
  "SVG Path inside SVG_6": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M923 283.6')]])[5]`,
  "SVG Path inside SVG_7": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M923 283.6')]])[6]`,
  "SVG Path inside SVG_8": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M923 283.6')]])[3]`,
  "SVG Path inside SVG_9": `(//*[name()='svg'][.//*[name()='path' and contains(@d,'M257.7 752')]])[1]`,
  "SVG_1": `svg[data-icon="eye-invisible"]`,
  "SVG_2": `svg[data-icon="arrow-left"]`,
  "SVG_3": `svg[viewBox="0 0 512 512"]`,
  "SVG_4": `svg[data-icon="arrow-right"]`,
  "SVG_5": `svg[viewBox="0 0 576 512"]`,
  "SVG_6": `svg[data-icon="bars"]`,
  "SVG_7": `svg[data-icon="appstore"]`,
  "SVG_8": `svg[viewBox="0 0 44 44"]`,
  "Button with Text Add Your First Address": `//button[normalize-space()='Add Your First Address']`,
  "Div starting with Text 1": `((((((//div[starts-with(normalize-space(), '1')])[1]//div)[1]//div)[5]//div)[10]//div)[1]//div)[1]`,
  "Div starting with Text 1_1": `((//div[starts-with(normalize-space(), '1')])[1]//div)[1]`,
  "Div with Text 1": `(//div[normalize-space()='1'])[1]`,
  "H1": `(//h1[contains(text(), 'Logitech MX Master 3 Wireless ')])[1]`,
  "H1 with Text Demo E-commerce Testing Store": `//h1[normalize-space()='Demo E-commerce Testing Store']`,
  "H1 with Text JBL Charge 4 Bluetooth Speaker": `(//h1[normalize-space()='JBL Charge 4 Bluetooth Speaker'])[1]`,
  "H2": `//h2[contains(text(), 'Logitech MX Master 3 Wireless ')]`,
  "H2 with Text JBL Charge 4 Bluetooth Speaker": `//h2[normalize-space()='JBL Charge 4 Bluetooth Speaker']`,
  "H2 with Text Your Cart": `//h2[normalize-space()='Your Cart']`,
  "H3": `//h3[contains(text(), 'Logitech MX Master 3 Wireless ')]`,
  "Html": `html[lang="en"] > body`,
  "Img with alt camera": `img[alt="camera"]`,
  "Label with for email": `label[for="email"]`,
  "Label with for password": `label[for="password"]`,
  "Li with Text About Us": `(//li[normalize-space()='About Us'])[1]`,
  "Li with Text All Products": `(//li[normalize-space()='All Products'])[1]`,
  "Li with Text Home": `(//li[normalize-space()='Home'])[1]`,
  "P with Text  12 000": `(//p[normalize-space()='₹12,000'])[1]`,
  "P with Text Addresses": `//p[normalize-space()='Addresses']`,
  "P with Text Log Out": `//p[normalize-space()='Log Out']`,
  "SVG": `svg[viewBox="0 0 576 512"]`,
};

module.exports = { locators };
